name: FindCode Action
description: 'Run FindCode scanning tool'
inputs:
  target-path:
    description: 'Path to the target code'
    required: true
  code-type:
    description: 'Types of code frameworks'
    required: true
  output-report:
    description: 'Path to the output report'
    required: true
  target-code:
    description: 'Fill in the scan logic through functions supported by the rules engine'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target-path }}
    - ${{ inputs.code-type }}
    - ${{ inputs.output-report }}
    - ${{ inputs.target-code }}